name: Netto TR Listesi

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install requests # <-- requests kütüphanesini yüklüyoruz

    - name: Run M3U processing script
      env:
        M3U_SOURCE_URL: "https://raw.githubusercontent.com/Latte-tester/netto/refs/heads/main/world.m3u8"
      run: python .github/scripts/netto_tr.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'

        git add netto-special/netto-tr.m3u

        if git diff --staged --quiet; then
          echo "Değişiklik olmadığından devam ediliyor."
        else
          echo "Changes detected in netto-tr.m3u. Committing..."
          git commit -m "♻️ Netto kanalları güncellendi"
          git push
          echo "Değişiklikler commit edildi ve uygulandı."
        fi